heat_template_version: 2015-04-30

description: Template for microservices

parameters:

  w_instances_count:
    type: number
    label: W instances count
    default: 1
    description: Number of w instances to deploy

  s_instances_count:
    type: number
    label: S instances count
    default: 1
    description: Number of s instances to deploy

  galera_instances_count:
    type: number
    label: Galera instances count
    default: 1
    description: Number of galera instances to deploy

resources:

  critical_net:
    type: critical_network.yaml

  w_servers:
    type: OS::Heat::ResourceGroup
    depends_on: critical_net
    properties:
      count: { get_param: w_instances_count }
      resource_def:
        type: instance_with_volume.yaml
        properties:
          service_name: "w"
          instance_index: "%index%"
          network: critical_network

  s_servers:
    type: OS::Heat::ResourceGroup
    depends_on: critical_net
    properties:
      count: { get_param: s_instances_count }
      resource_def:
        type: instance_with_volume.yaml
        properties:
          service_name: "s"
          instance_index: "%index%"
          network: critical_network

  galera_first_node_server:
    type: instance_with_volume.yaml
    depends_on: critical_net
    properties:
      service_name: "galera_f"
      instance_index: "0"
      network: critical_network

  galera_other_node_servers:
    type: OS::Heat::ResourceGroup
    depends_on: critical_net
    properties:
      count: { get_param: galera_instances_count }
      resource_def:
        type: instance_with_volume.yaml
        properties:
          service_name: "galera_o"
          instance_index: "%index%"
          network: critical_network

outputs:
  w_adresses:
    description: IP addresses of w
    value: { get_attr: [ w_servers, ip_addresses ] }

  s_adresses:
    description: IP addresses of s
    value: { get_attr: [ s_servers, ip_addresses ] }

  galera_first_node_server:
    description: IP address of galera_first_node instances
    value: { get_attr: [ galera_first_node_server, ip_addresses ] }

  galera_other_node_servers:
    description: IP addresses of galera other nodes
    value: { get_attr: [ galera_other_node_servers, ip_addresses ] }