heat_template_version: 2015-04-30

description: Template for microservices

parameters:
  consul_server_instances_count:
    type: number
    label: Consul server instances count
    default: 1
    description: Number of consul server instances to deploy
    modulo: { step: 2, offset: 1 }

  b_instances_count:
    type: number
    label: B instances count
    default: 1
    description: Number of b instances to deploy

  w_instances_count:
    type: number
    label: W instances count
    default: 1
    description: Number of w instances to deploy

  mysql_instances_count:
    type: number
    label: Mysql instances count
    default: 1
    description: Number of mysql instances to deploy

  appliWeb_instances_count:
    type: number
    label: AppliWeb instances count
    default: 1
    description: Number of appliWeb instances to deploy

resources:

  consul_servers:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: consul_server_instances_count }
      resource_def:
        type: instance_with_volume.yaml
        properties:
          service_name: "consul_server"
          instance_index: "%index%"

  w_servers:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: w_instances_count }
      resource_def:
        type: instance_with_volume.yaml
        properties:
          service_name: "w"
          instance_index: "%index%"

  b_servers:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: b_instances_count }
      resource_def:
        type: instance_with_volume.yaml
        properties:
          service_name: "b"
          instance_index: "%index%"

  mysql_servers:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: mysql_instances_count }
      resource_def:
        type: instance_with_volume.yaml
        properties:
          service_name: "mysql"
          instance_index: "%index%"

  appliWeb_servers:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: appliWeb_instances_count }
      resource_def:
        type: instance_with_volume.yaml
        properties:
          service_name: "appliWeb"
          instance_index: "%index%"

outputs:
  b:
    description: IP addresses of b
    value: { get_attr: [ b_servers, ip_addresses ] }

  w:
    description: IP addresses of w
    value: { get_attr: [ w_servers, ip_addresses ] }

  consul_server:
    description: IP addresses of consul_servers
    value: { get_attr: [ consul_servers, ip_addresses ] }

  mysql:
    description: IP addresses of mysql instances
    value: { get_attr: [ mysql_servers, ip_addresses ] }

  appliWeb:
    description: IP addresses of appliWeb instances
    value: { get_attr: [ appliWeb_servers, ip_addresses ] }