---
- hosts: b
  user: centos
  tasks:
    - name: Send b microservice directory
      copy:
        src: ../cloud_native_app/microservices/b
        dest: /home/centos/

    - name: Build b docker image
      shell:
        chdir: ~/b
        cmd: sudo docker build -t b:b .

    - name: Run b docker container
      shell:
        cmd: docker run -d -p 8090:8090 b:b
      become: true

    - name: Run consul agent and join cluster
      shell:
        cmd: screen -m -d consul agent -data-dir=/var/consul.d -bind={{ ansible_eth0.ipv4.address }} -join={{ groups['consul_server'][0] }} -config-dir=/etc/consul.d

    - yum:
        name: epel-release
        state: latest
      become: true

    - name: Install pip
      yum:
        name: python-pip
        state: latest
      become: true

    - name: Install python-consul
      pip:
        name: python-consul
      become: true

    - name: Install requests
      pip:
        name: requests
      become: true

    - name: Register b service
      consul:
        service_name: b
        service_port: 8090
        script: curl http://localhost:8090/
        interval: 10s