---
- hosts: galera_all_nodes
  user: centos
  vars:
    galera_cluster_members: "{{ groups['galera_all_nodes'] }}"
    galera_cluster_joined: "{{ groups['galera_all_nodes'] | join (',') }}"
    my_adress: "{{ ansible_eth0.ipv4.address }}"
  tasks:
    - name: Install screen
      yum:
        name: screen
      become: true

    - name: Download consul
      get_url:
        url: https://releases.hashicorp.com/consul/0.7.1/consul_0.7.1_linux_amd64.zip
        dest: /home/centos
      become: true

    - name: Install Unzip
      yum:
        name: unzip
        state: latest
      become: true

    - name: Unarchive consul
      unarchive:
        src: /home/centos/consul_0.7.1_linux_amd64.zip
        dest: /usr/local/bin/
        copy: no
      become: true

    - name: Create consul data dir
      file:
        path: /var/consul.d
        state: directory
        mode: 0777
      become: true

    - name: Create consul config dir
      file:
        path: /etc/consul.d
        state: directory
        mode: 0777
      become: true

    - name: Flush ip tables
      shell:
        cmd: iptables -F
      become: true

    - name: Disable SELinux
      shell:
        cmd: setenforce 0
      become: true

    - name: Install Percona repo
      yum:
        name: http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm
      become: true

    - name: Install epel repo
      yum:
        name: epel-release
      become: true

    - name: Install socat
      yum:
        name: socat
      become: true

    - name: Install Percona cluster
      yum:
        name: Percona-XtraDB-Cluster-56
      become: true

    - name: Config mysql
      script: setup_mysql_conf.sh {{ galera_cluster_joined }} {{ my_adress }}
