---
- hosts: galera_other_node
  user: centos
  tasks:
    - name: Install screen
      yum:
        name: screen
      become: true

    - name: Start mysql
      shell:
        cmd: screen -m -d sudo mysqld

    - name: Run consul agent and join cluster
      shell:
        cmd: screen -m -d consul agent -data-dir=/var/consul.d -config-dir=/etc/consul.d -bind={{ ansible_eth0.ipv4.address }} -join={{ groups['consul_server'][0] }}

    - name: Wait for agent to run or fail
      shell:
        cmd: consul members
      register: result
      until: result.stdout.find("{{ inventory_hostname }}") != -1
      retries: 5
      delay: 5

    #TODO: Mysql healt check
    - name: Register mysql service
      uri:
        url: http://localhost:8500/v1/agent/service/register
        method: PUT
        body: "{{ lookup('file','register_mysql.json') }}"
        body_format: json