---
- hosts: p
  user: centos
  vars:
   os_pass: "{{ lookup('env','OS_PASSWORD') }}"
  tasks:

    - name: Send p microservice directory
      copy:
        src: ../cloud_native_app/microservices/p
        dest: /home/centos/

    - name: Run consul agent and join cluster
      shell:
        cmd: screen -m -d consul agent -data-dir=/var/consul.d -config-dir=/etc/consul.d -bind={{ ansible_eth0.ipv4.address }} -join={{ groups['consul_server'][0] }}

    - name: Wait for agent to run or fail
      shell:
        cmd: consul members
      register: result
      until: result.stdout.find("{{ inventory_hostname }}") != -1
      retries: 5
      delay: 5

    - name: Stop p docker container if already running
      shell:
        cmd: sudo docker rm $(sudo docker stop $(sudo docker ps -a -q  --filter ancestor=p:p))
      ignore_errors: yes

    - name: Build p docker image
      shell:
        chdir: ~/p
        cmd: sudo docker build -t p:p .

    - name: Run p docker container
      shell:
        cmd: docker run --network="host" -e OS_PASSWORD={{ os_pass }} -d -p 8090:8090 -p 8500:8500 -p 5000:5000 p:p
      become: true

    - name: Register p service
      uri:
        url: http://localhost:8500/v1/agent/service/register
        method: PUT
        body: "{{ lookup('file','register_p.json') }}"
        body_format: json
