---
- hosts: w
  user: centos
  tasks:
    - name: Send w microservice directory
      copy:
        src: ../cloud_native_app/microservices/w
        dest: /home/centos/

    - name: Build w docker image
      shell:
        chdir: ~/w
        cmd: sudo docker build -t w:w .

    - name: Run w docker container
      shell:
        cmd: docker run --network=host -d -p 8090:8090 -p 8500:8500 w:w
      become: true

    - name: Run consul agent and join cluster
      shell:
        cmd: screen -m -d consul agent -data-dir=/var/consul.d -bind={{ ansible_eth0.ipv4.address }} -join={{ groups['consul_server'][0] }} -config-dir=/etc/consul.d

    - name: Install python-consul
      pip:
        name: python-consul
      become: true

    - name: Install requests
      pip:
        name: requests
      become: true

    - name: Register w service
      consul:
        service_name: w
        service_port: 8090
        script: curl http://localhost:8090/
        interval: 10s
